version: "3.8"
services:
  # adding a backend service
  backend:
    # how the image is built and from where, here it is building from Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    command: "python main.py"
    # what ports it should run on, here it is listening to the app on port 8080 and forwarding everything to port 8080
    ports:
      - 8001:5000
    extra_hosts:
      - "docker.for.linux.localhost:172.17.0.1"
    # here every change made to . will be also be push to /app
    volumes:
      - .:/app
    # this means the db container will run first before running the backend container
    depends_on:
      - db

  #  adding a queue service
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: "python consumer.py"
    depends_on:
      - db

  #  adding a database service
  db:
    image: mysql:5.7.22
    container_name:
      main-mysql
      # db goes down sometimes this enables db to always restart when it does
    restart: always
    # adding environment variables
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root

    # expose:
    #   - 33066
    # all the files in var/lib/mysql will be reflected in dbdata
    volumes:
      - .dbdata:/var/lib/mysql

    # add port to listen to (not required at all) but we can use it to see what is in the database
    # so here we are mapping everything from 3306 to 33066 .
    ports:
      - 33067:3306
    # extra_hosts:
    #   - "docker.for.linux.localhost:$DOCKERHOST"
